// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SESSION_SECRET_KEY: string;
	CF_ACCOUNT_ID: string;
	CF_TOKEN: string;
	DB: D1Database;
}
